version: '3.1'

services:

  api:
    image: mario21ic/api-demo
    build:
      context: ./
    depends_on:
      - db
    volumes:
      - ./:/apps/
    command: ["python3", "main.py"]
    ports:
      - 8080:8080

  db:
    image: mysql:5.5
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: myclave


